
package bank.soap.client.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceImpl", targetNamespace = "http://soap.bank/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceImpl {


    /**
     * 
     * @param amount
     * @param from
     * @param to
     * @throws IOException_Exception
     * @throws OverdrawException_Exception
     * @throws InactiveException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transfer", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.TransferResponse")
    @Action(input = "http://soap.bank/ServiceImpl/transferRequest", output = "http://soap.bank/ServiceImpl/transferResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/transfer/Fault/IOException"),
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.bank/ServiceImpl/transfer/Fault/InactiveException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://soap.bank/ServiceImpl/transfer/Fault/OverdrawException")
    })
    public void transfer(
        @WebParam(name = "from", targetNamespace = "")
        String from,
        @WebParam(name = "to", targetNamespace = "")
        String to,
        @WebParam(name = "amount", targetNamespace = "")
        double amount)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param number
     * @param amount
     * @throws OverdrawException_Exception
     * @throws IOException_Exception
     * @throws InactiveException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.WithdrawResponse")
    @Action(input = "http://soap.bank/ServiceImpl/withdrawRequest", output = "http://soap.bank/ServiceImpl/withdrawResponse", fault = {
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.bank/ServiceImpl/withdraw/Fault/InactiveException"),
        @FaultAction(className = OverdrawException_Exception.class, value = "http://soap.bank/ServiceImpl/withdraw/Fault/OverdrawException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/withdraw/Fault/IOException")
    })
    public void withdraw(
        @WebParam(name = "number", targetNamespace = "")
        String number,
        @WebParam(name = "amount", targetNamespace = "")
        double amount)
        throws IOException_Exception, InactiveException_Exception, OverdrawException_Exception
    ;

    /**
     * 
     * @param number
     * @param amount
     * @throws IOException_Exception
     * @throws InactiveException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deposit", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.DepositResponse")
    @Action(input = "http://soap.bank/ServiceImpl/depositRequest", output = "http://soap.bank/ServiceImpl/depositResponse", fault = {
        @FaultAction(className = InactiveException_Exception.class, value = "http://soap.bank/ServiceImpl/deposit/Fault/InactiveException"),
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/deposit/Fault/IOException")
    })
    public void deposit(
        @WebParam(name = "number", targetNamespace = "")
        String number,
        @WebParam(name = "amount", targetNamespace = "")
        double amount)
        throws IOException_Exception, InactiveException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isActive", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.IsActive")
    @ResponseWrapper(localName = "isActiveResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.IsActiveResponse")
    @Action(input = "http://soap.bank/ServiceImpl/isActiveRequest", output = "http://soap.bank/ServiceImpl/isActiveResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/isActive/Fault/IOException")
    })
    public boolean isActive(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccountNumbers", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.GetAccountNumbers")
    @ResponseWrapper(localName = "getAccountNumbersResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.GetAccountNumbersResponse")
    @Action(input = "http://soap.bank/ServiceImpl/getAccountNumbersRequest", output = "http://soap.bank/ServiceImpl/getAccountNumbersResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/getAccountNumbers/Fault/IOException")
    })
    public List<String> getAccountNumbers()
        throws IOException_Exception
    ;

    /**
     * 
     * @param owner
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.CreateAccountResponse")
    @Action(input = "http://soap.bank/ServiceImpl/createAccountRequest", output = "http://soap.bank/ServiceImpl/createAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/createAccount/Fault/IOException")
    })
    public String createAccount(
        @WebParam(name = "owner", targetNamespace = "")
        String owner)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns boolean
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeAccount", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.CloseAccount")
    @ResponseWrapper(localName = "closeAccountResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.CloseAccountResponse")
    @Action(input = "http://soap.bank/ServiceImpl/closeAccountRequest", output = "http://soap.bank/ServiceImpl/closeAccountResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/closeAccount/Fault/IOException")
    })
    public boolean closeAccount(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns double
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.GetBalanceResponse")
    @Action(input = "http://soap.bank/ServiceImpl/getBalanceRequest", output = "http://soap.bank/ServiceImpl/getBalanceResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/getBalance/Fault/IOException")
    })
    public double getBalance(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

    /**
     * 
     * @param number
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOwner", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.GetOwner")
    @ResponseWrapper(localName = "getOwnerResponse", targetNamespace = "http://soap.bank/", className = "bank.soap.client.jaxws.GetOwnerResponse")
    @Action(input = "http://soap.bank/ServiceImpl/getOwnerRequest", output = "http://soap.bank/ServiceImpl/getOwnerResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://soap.bank/ServiceImpl/getOwner/Fault/IOException")
    })
    public String getOwner(
        @WebParam(name = "number", targetNamespace = "")
        String number)
        throws IOException_Exception
    ;

}
